database:
  - {
    connectname: "test1",
    addr: "127.0.0.1",
    port: 3306,
    username: "",
    password: "",
    charset: "utf8",
    dbname: ""
  }
  - {
    connectname: "test2",
    addr: "127.0.0.1",
    port: 3306,
    username: "",
    password: "",
    charset: "utf8",
    dbname: ""
  }
  - {
    connectname: "test3",
    addr: "127.0.0.1",
    port: 3306,
    username: "",
    password: "",
    charset: "utf8",
    dbname: ""
  }